services:
  - type: web
    name: civil-defense-site
    env: static
    rootDir: static-site
    buildCommand: echo "No build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
